USE WISE_STAGING
GO
/*T_MKT_MARKETPLACE_ACQ_REQ*/
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_ADDR         VARCHAR(200)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_RT           VARCHAR(3  )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_RW           VARCHAR(3  )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_PROVINCE     VARCHAR(100)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_CITY         VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_SUB_DISTRICT VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_VILLAGE      VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_CITY_ID      VARCHAR(10 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD RT                  VARCHAR(3  )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD RW                  VARCHAR(3  )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD PROVINCE            VARCHAR(100)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SUB_DISTRICT        VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD VILLAGE             VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SOA                 VARCHAR(100)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD SURVEY_SUB_ZIP_CODE VARCHAR(20 ) 
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD LEGAL_SUB_ZIP_CODE VARCHAR(20 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ADD ID_STATUS           VARCHAR(20)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ_REQ ALTER COLUMN SOURCE_DATA	   VARCHAR(50)
 
/*T_MKT_MARKETPLACE_ACQ*/
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_ADDR         VARCHAR(200)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_RT           VARCHAR(3  )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_RW           VARCHAR(3  )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_PROVINCE     VARCHAR(100)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_CITY         VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_SUB_DISTRICT VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_VILLAGE      VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_CITY_ID      VARCHAR(10 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD RT                  VARCHAR(3  )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD RW                  VARCHAR(3  )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD PROVINCE            VARCHAR(100)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SUB_DISTRICT        VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD VILLAGE             VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SOA                 VARCHAR(100)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SURVEY_SUB_ZIP_CODE VARCHAR(20 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD LEGAL_SUB_ZIP_CODE VARCHAR(20 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD ID_STATUS           VARCHAR(100)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD AGRMNT_NO           VARCHAR(20 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD PO_NO               VARCHAR(50 )
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD PO_DATE             DATETIME
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD PO_DP               NUMERIC
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD PO_TENOR            INT
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD INSTALMENT_AMT      NUMERIC
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD OFFICE_CODE         VARCHAR(10)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD SEND_FLAG_MSS       CHAR(1) DEFAULT '0'
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ADD ORDER_NO_MSS         VARCHAR(100)
ALTER TABLE  T_MKT_MARKETPLACE_ACQ ALTER COLUMN SOURCE_DATA	   VARCHAR(50) 


/*M_MKT_MARKETPLACE_PARTNER*/
ALTER TABLE  M_MKT_MARKETPLACE_PARTNER ADD FLAG_MASTER_PARTNER    VARCHAR(20)

/*M_MKT_MARKETPLACE_PRODUCT_TYPE*/
ALTER TABLE  M_MKT_MARKETPLACE_PRODUCT_TYPE ADD FLAG_MASTER_PRODUCT    VARCHAR(20)

/*M_MKT_MARKETPLACE_STATUS*/
ALTER TABLE  M_MKT_MARKETPLACE_STATUS ADD STATUS_MSS_WISE    VARCHAR(20)

/*T_MKT_MARKETPLACE_STATUS*/
ALTER TABLE  T_MKT_MARKETPLACE_STATUS ADD STATUS_MSS_WISE    VARCHAR(20)