USE WISE_STAGING
GO
 
ALTER TABLE M_MKT_POLO_QUESTION_LABEL ADD CONSTRAINT CONST_M_MKT_POLO_QUESTION_LABEL UNIQUE (QUESTION_CODE); 
ALTER TABLE M_MKT_POLO_QUESTION_LIST ADD CONSTRAINT CONST_M_MKT_POLO_QUESTION_LIST UNIQUE (QUESTION_IDENTIFIER); 
ALTER TABLE M_MKT_POLO_QUESTIONGROUP_H ADD CONSTRAINT CONST_M_MKT_POLO_QUESTIONGROUP_H UNIQUE (QUESTIONGROUP_NAME); 
ALTER TABLE M_MKT_POLO_QUESTIONGROUP_D ADD CONSTRAINT CONST_M_MKT_POLO_QUESTIONGROUP_D UNIQUE (M_MKT_POLO_QUESTIONGROUP_H_ID,QUESTION_IDENTIFIER,QUESTION_API); 

ALTER TABLE M_MKT_POLO_PARAMETER ADD CONSTRAINT CONST_M_MKT_POLO_PARAMETER UNIQUE (PARAMETER_ID,PARAMETER_TYPE);  
 
